const en = {
  source: "Source and layout", appearanceSection: "Appearance", binsSection: "Bins",
  entities: "Waste sensors or calendars", title: "Title", layout: "Layout",
  appearance: "Appearance", density: "Density", days_to_show: "Days to show",
  max_groups: "Visible date groups", show_artwork: "Show bin artwork",
  show_updated: "Show provider update time", show_manage_bins: "Show Manage bins shortcut",
  show_source: "Show source names", locale: "Language override (optional)",
  compact: "Compact", hero: "Hero", schedule: "Schedule", overview: "Overview",
  native: "Native Home Assistant", modern: "Modern", minimal: "Minimal", comfortable: "Comfortable",
  sourceHelp: "Select one authoritative source per address. For Waste Collection Schedule, choose the combined sensor with Generic details (All attributes in visual bin controls). Calendars also work.",
  unsupported: "No structured schedule is exposed. Open the sensor settings and choose Generic / All attributes.",
  binsHelp: "Integration colors apply until you choose an override. Shared bin definitions stay in Waste Collection Schedule.",
  rangeHelp: "Calendar bin choices come from events in the selected date range. Bins without records can be added in Advanced.",
  noBins: "No bins found in the supplied schedule.", calendarLoading: "Loading calendar bins…",
  calendarFailed: "Some calendar bins could not be loaded. Check the source entity or try again.",
  customize: "Edit bin", displayName: "Display name", localColor: "Local bin color",
  inheritedColor: "Inherited card color", integrationColor: "Integration color", localColorStatus: "Local color",
  varyingColors: "Integration colors vary by bin.", neutralColor: "No integration color is available; artwork stays neutral.",
  resetInherited: "Use inherited card color", resetIntegration: "Use integration color",
  hide: "Hide this collection", hidden: "Hidden", local: "Customized", integration: "Integration",
  done: "Done", remove: "Reset this override", matching: "Advanced matching and icon",
  type: "Category ID or exact calendar name", binSource: "Source entity (optional)",
  label: "Exact bin name (optional)", icon: "Icon (mdi:…)", color: "Local color (#RRGGBB)",
  advanced: "Advanced settings", advancedOverride: "Add a category or missing bin override",
  overrideHelp: "Use the exact type ID, or the complete collection name for older sensors and calendars.",
  addOverride: "Add collection override", tap: "Tap action", details: "View schedule", "more-info": "Entity details",
  overrideLimit: "This card supports up to 100 overrides. Reset an unused override before adding another.",
  navigate: "Open dashboard", none: "No action", navigationPath: "Dashboard path", retry: "Retry",
};
const pl: typeof en = {
  source: "Źródło i układ", appearanceSection: "Wygląd", binsSection: "Pojemniki",
  entities: "Sensory odpadów lub kalendarze", title: "Tytuł", layout: "Układ",
  appearance: "Wygląd", density: "Odstępy", days_to_show: "Liczba dni", max_groups: "Widoczne grupy terminów",
  show_artwork: "Pokaż ilustracje pojemników", show_updated: "Pokaż czas aktualizacji źródła",
  show_manage_bins: "Pokaż skrót Zarządzaj pojemnikami", show_source: "Pokaż nazwy źródeł", locale: "Język (opcjonalnie)",
  compact: "Kompaktowy", hero: "Wyróżniony", schedule: "Harmonogram", overview: "Przegląd",
  native: "Natywny Home Assistant", modern: "Nowoczesny", minimal: "Minimalistyczny", comfortable: "Wygodne",
  sourceHelp: "Wybierz jedno główne źródło dla każdego adresu. W Waste Collection Schedule wybierz sensor zbiorczy ze szczegółami Generic (Wszystkie atrybuty w ustawieniach wizualnych). Możesz też użyć kalendarza.",
  unsupported: "Sensor nie udostępnia danych harmonogramu. Otwórz jego ustawienia i wybierz Generic / Wszystkie atrybuty.",
  binsHelp: "Kolory integracji obowiązują do wybrania własnych. Wspólne definicje pojemników pozostają w Waste Collection Schedule.",
  rangeHelp: "Pojemniki kalendarza pochodzą z wydarzeń w wybranym zakresie dat. Pojemniki bez terminów można dodać w ustawieniach zaawansowanych.",
  noBins: "Brak pojemników w udostępnionym harmonogramie.", calendarLoading: "Ładowanie pojemników kalendarza…",
  calendarFailed: "Nie udało się wczytać niektórych pojemników kalendarza. Sprawdź encję źródłową lub spróbuj ponownie.",
  customize: "Edytuj pojemnik", displayName: "Wyświetlana nazwa", localColor: "Własny kolor pojemnika",
  inheritedColor: "Odziedziczony kolor karty", integrationColor: "Kolor integracji", localColorStatus: "Własny kolor",
  varyingColors: "Kolory integracji różnią się między pojemnikami.", neutralColor: "Brak koloru integracji; ilustracje pozostają neutralne.",
  resetInherited: "Użyj odziedziczonego koloru karty", resetIntegration: "Użyj koloru integracji",
  hide: "Ukryj ten odbiór", hidden: "Ukryty", local: "Dostosowany", integration: "Integracja",
  done: "Gotowe", remove: "Przywróć ustawienia tego wpisu", matching: "Zaawansowane dopasowanie i ikona",
  type: "ID kategorii lub dokładna nazwa kalendarza", binSource: "Encja źródłowa (opcjonalnie)",
  label: "Dokładna nazwa pojemnika (opcjonalnie)", icon: "Ikona (mdi:…)", color: "Własny kolor (#RRGGBB)",
  advanced: "Ustawienia zaawansowane", advancedOverride: "Dodaj wpis dla kategorii lub brakującego pojemnika",
  overrideHelp: "Użyj dokładnego ID kategorii lub pełnej nazwy odbioru ze starszych sensorów i kalendarzy.",
  addOverride: "Dodaj wpis odbioru", tap: "Akcja po dotknięciu", details: "Zobacz harmonogram", "more-info": "Szczegóły encji",
  overrideLimit: "Karta obsługuje do 100 własnych wpisów. Usuń nieużywany wpis przed dodaniem kolejnego.",
  navigate: "Otwórz pulpit", none: "Brak akcji", navigationPath: "Ścieżka pulpitu", retry: "Spróbuj ponownie",
};
export const editorStrings = (locale: string): typeof en => locale.toLowerCase().startsWith("pl") ? pl : en;
export type EditorStrings = typeof en;
